return {
  "williamboman/mason.nvim",
  build = ":MasonUpdate",
  opts = {
    ensure_installed = {
      "lua-language-server",
      "stylua",
      "shfmt",
      "eslint-lsp",
      "prettierd",
      "marksman",
      "markdownlint",
      "clangd",
      "clang-format",
      "latexindent",
      "bash-language-server",
      "pyright",
      "ruff",
      "debugpy",
      "black",
      "shellcheck",
      "html-lsp",
      "css-lsp",
      "json-lsp",
      "typescript-language-server",
      "gopls",
      "golangci-lint",
      "goimports",
      "golines",
      "gofumpt",
      "delve",
      "texlab",
      "harper-ls",
      "qmlls",
      "sqls",
      "sqlfluff",
    },
    max_concurrent_installers = 10,
  },
}
